### ISSUE TITLE
MLab üzerindne yeni connection alınması

### ISSUE THREAD

**Issue by yakintech** [yakintech/AngularECommerce#4]

**Comment by yildirimdamla** [comment]
https://account.mongodb.com/account/login adresi üzerinden kullanıcı hesabı oluşturuldu.
Email Address: fed.bilgeadam@yandex.com
Password: Bilge2020


Nodejs erişim adresi:
mongoose.connect(
  "mongodb+srv://FedBilgeAdam:FedBilgeAdam@cluster0.msq3p.mongodb.net/FedBilgeAdam?retryWrites=true&w=majority",
  { useNewUrlParser: true, useUnifiedTopology: true }
);
